name: sample-stack-templatedasfas
description: Uncomment and modify the sections to configure your own amazing stack.
branding:
  icon: bell # https://feathericons.com/
  color: blue # hex accepted

#-------------------------------------------------------------
configs:
  # Meta data for creating the new repository
  # repo-metadata:
  #   parameters:
  #     secrets: 
  #     - name: sample_secret
  #       value: ${{inputs.secret}} # example of a reference
  #     topics:
  #     - sample_topic_1
  #     - sample_topic_2
      
  # Branch Protection rules
  branches:
    - name: release_v? #branch name or pattern you want to protect
      parameters:
        enforce-admins: true
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          require-code-owner-reviews: true
          required-approving-review-count: 1 # integer
        allow-force-pushes: true
        allow-deletions: true

  # Configure an environment
  # environments: 
  #   - name: staging
  #     parameters: 
  #       protected-branches: true / false
  #       allowed-branch-rules:
  #         - main/* # pattern similar to branch protection
  #       wait-timer: 50 # in seconds
  #       reviewers:
  #         - name: torvalds # valid username of reviewer
  #           type: User
  #       secrets:
  #         - name: SPN_ID
  #           value: ${{inputs.secret}}

  # Security and configuration settings to be enabled/disabled
  # security:
  #   parameters: 
  #     vulnerability-alerts: true / false
  #     automated-security-fixes: true # can be true only if vulnerability-alerts is true


#-------------------------------------------------------------
# GitHub Apps to be installed
# just provide the slugs
# github-apps:
# - slug: sample1
# - slug: sample2


#-------------------------------------------------------------
# Initialization workflow to run
# This workflow file will NOT be part of the stack (new repo created). 
# workflow could use the stack inputs using the notation : ${{ github.event.inputs.name }}
# init:
#  uses: "setup.yml" # you would have to create a workflow - .github/workflows/setup.yml
